"""Vega expression emitter for the house numeral register.

Vega-Lite paints axis ticks and mark-value labels by running its own,
in-browser d3-format implementation directly on a raw d3 spec string.
``format_d3``'s analytic/narrative notation post-process is Python-side and
never runs on those values, so a value Vega-Lite paints can show d3's raw
SI suffix (``200M``) but never the house register a value dbt charts formats
itself would (``200 M`` / ``200mn``).

This module builds the Vega *expression* equivalent of that post-process: a
``format(...)`` call chained through the same suffix substitutions
``format_d3`` applies, generated by iterating the same
``_D3_TO_ANALYTIC``/``_D3_TO_NARRATIVE`` maps ``render.format_utils`` already
imports for the Python-side version — one register, two emitters, never two
suffix vocabularies.
"""

from __future__ import annotations

import json

from dbt_charts.core.diagnostics.codes_render import ERR_NUMERAL_EXPR_EMPTY_SPEC
from dbt_charts.core.render.errors import RenderError
from dbt_charts.core.text.format_d3 import (
    _D3_TO_ANALYTIC,
    _D3_TO_NARRATIVE,
    Notation,
    _is_si_spec,
)
from dbt_charts.core.text.numeral_scale import SUB_UNIT_SCIENTIFIC_FLOOR

_NOTATION_MAPS: dict[Notation, dict[str, str]] = {
    "analytic": _D3_TO_ANALYTIC,
    "narrative": _D3_TO_NARRATIVE,
}


def numeral_vega_expr(
    value_expr: str, format_spec: str, notation: Notation | None = None
) -> str:
    """Vega expression for the SI notation post-process ``format_d3`` applies.

    ``value_expr`` is the Vega datum reference to format verbatim (e.g.
    ``datum.value`` on an axis, ``datum.<field>`` inside a ``calculate``
    transform for a mark label). Only SI (``s``-type) specs with an explicit
    ``notation`` carry the house-register post-process, matching
    ``format_d3``'s own behavior — a non-SI spec or a call without
    ``notation`` emits a plain ``format(...)`` call with no substitution
    chain. Round-aware (``format_d3``'s ``~``-trim injection) for the same
    reason: Vega runs its own d3 on the bare spec and never sees the Python
    post-process, so this is the only place that gap can close.

    Callers on the predefined-format path pass ``notation="analytic"`` or
    ``"narrative"``; callers on the native-d3 path (inline specs, user aliases)
    omit it so no post-process runs — matching ``format_d3``'s own contract.

    ``format_spec`` must be a d3 spec as already resolved by ``resolve_format``
    — i.e., for predefined names, ``resolve_format`` has already baked the
    round-aware ``~`` trim into the spec. This function does NOT inject ``~``
    itself (contrast the old behavior). Predefined specs arrive pre-trimmed;
    inline specs arrive without ``~`` and stay that way, so Python and Vega
    agree on the same digit count.

    Not null-guarded: production callers are ``inject_axis_numeral_expr``
    (``vl_field_maps.py``, dividing ``datum.value`` by a magnitude first —
    axis ticks are also never null) and ``_house_register_text_encoding``
    (``value_labels.py``, passing a raw, genuinely nullable row field
    directly). Neither needs a guard here: verified via ``vl_convert``,
    Vega's ``format(null, spec)`` renders the literal text ``"null"`` — the
    same text the pre-existing ``text.format`` branch already renders for a
    null cell (no ``calculate``, format applied directly on the encoding).
    A guard here would change nothing a user can see; it would only move
    where the same ``"null"`` text comes from.

    Reproduces only ``format_d3``'s spec-plus-notation formatting, not its
    ``prefix``/``suffix`` wrapping — those are a separate string
    concatenation the caller applies outside this expression.

    Raises:
        RenderError: ``format_spec`` is empty (``ERR_NUMERAL_EXPR_EMPTY_SPEC``).
            ``format_d3`` treats an empty spec as "no d3 formatting" and
            returns the bare Python value instead of calling d3 — a
            different code path this translator doesn't model (Python's and
            JS's default numeral rendering aren't the same string), so it
            fails fast rather than emitting a ``format(...)`` call that
            would silently diverge.
    """
    if not format_spec:
        raise RenderError.from_code(ERR_NUMERAL_EXPR_EMPTY_SPEC)

    call = f"format({value_expr},{json.dumps(format_spec)})"
    if notation is not None and _is_si_spec(format_spec):
        # Safe only because no current house suffix ends in a d3 map key
        # that iteration reaches later (e.g. analytic's " M" ends in "M",
        # already consumed by the time the loop gets there) — otherwise this
        # chain of sequential replacements could re-match output from an
        # earlier one, unlike format_d3's own first-match-wins loop. The
        # parity test's tier matrix would fail if a vocabulary change broke
        # that.
        for d3_suffix, house_suffix in _NOTATION_MAPS[notation].items():
            call = f"replace({call}, /{d3_suffix}$/, {json.dumps(house_suffix)})"

    return call


def sub_unit_guarded_vega_expr(
    value_expr: str, digit_expr: str, scientific_expr: str, at_least_one_expr: str
) -> str:
    """Paint a sub-1 value in digits, not through an SI spec's milli/micro prefix.

    Each argument after ``value_expr`` is the Vega text for that magnitude
    band: ``at_least_one_expr`` for |v| >= 1, else ``digit_expr``
    (``sub_unit_digit_format``), or ``scientific_expr``
    (``sub_unit_scientific_format``) below ``SUB_UNIT_SCIENTIFIC_FLOOR``;
    zero stays in ``digit_expr`` ("0", not "0e+0").
    """
    sub_one_e = (
        f"({value_expr} !== 0 && abs({value_expr}) < "
        f"{json.dumps(SUB_UNIT_SCIENTIFIC_FLOOR)} "
        f"? {scientific_expr} : {digit_expr})"
    )
    return f"(abs({value_expr}) < 1 ? {sub_one_e} : {at_least_one_expr})"
